{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
      /etc/nixos/sharedDependencies/configuration.nix
      /etc/nixos/sharedDependencies/system/mounts/myMedia.nix
      /etc/nixos/sharedDependencies/users/nanya.nix
    ];

  networking.hostName = "DesmosCalculator"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";


  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices."luks-0e2a40d9-c2b2-4367-8a94-4f10875a167b".device = "/dev/disk/by-uuid/0e2a40d9-c2b2-4367-8a94-4f10875a167b";

  # Enable the KDE Plasma Desktop Environment.
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true;

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    # If you want to use JACK applications, uncomment this
    #jack.enable = true;

    # use the example session manager (no others are packaged yet so this is enabled by default,
    # no need to redefine it in your config for now)
    #media-session.enable = true;
  };

  services.displayManager.sddm.wayland.enable = true;

  # Install firefox.
  programs.firefox.enable = true;

  environment.systemPackages = with pkgs; [
    alacritty
    asunder
    audacity
    discord
    jetbrains.idea-community-bin
    obsidian
    thunderbird
    tor-browser
    bitwarden-desktop
    kdePackages.filelight
    kdePackages.kate
    kdePackages.kdeconnect-kde
    kdePackages.kdevelop
    kdePackages.kimageformats
    signal-desktop
    qtcreator
    telegram-desktop
    minetest-mapserver
    zsh
  ];

  # Do not modify below here!  It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.  Please make changes
  # to /etc/nixos/configuration.nix instead.
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "ahci" "nvme" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/06a28f6b-12ac-4ec6-817a-8f0be3a5d06a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ea2d32d4-cba2-481b-b029-f184f56eacb7".device = "/dev/disk/by-uuid/ea2d32d4-cba2-481b-b029-f184f56eacb7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6A56-FC61";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/bd023222-e66d-4467-9e5f-dcdd12e1b802"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
